sbatch -n 4 job.sh
sbatch -n 5 job.sh
sbatch -n 8 job.sh
sbatch -n 10 job.sh
sbatch -n 16 job.sh
sbatch -n 20 job.sh
sbatch -n 25 job.sh
sbatch -n 32 job.sh
sbatch -n 40 job.sh
sbatch -n 50 job.sh
sbatch -n 64 job.sh
